name: Release

on:
  push:
    tags:
      - "*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Changelog
        id: changelog-parser
        uses: ocavue/changelog-parser-action@v1
        with:
          filePath: changelog.md
          removeMarkdown: false

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          CHANGELOG_BODY: "${{ fromJSON(steps.changelog-parser.outputs.parsed).versions[1].body }}"
        with:
          body: ${{ env.CHANGELOG_BODY }}
          name: 'v${{ github.ref_name }}'

